image: ubuntu:devel

stages:
    - build
    - check
    
before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install python3 python3-pip 

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install intltool yelp-tools gnome-pkg-tools libdbus-1-dev -y
    - apt-get install libgit2-glib-1.0-dev libglib2.0-dev libgtk-3-dev -y
    - apt-get install libgtksourceview-4-dev libgucharmap-2-90-dev libpeas-dev -y
    - apt-get install valac libvte-2.91-dev libzeitgeist-2.0-dev gedit-dev -y
    - apt-get install python3-dbus python-dbus-dev python3-gi appstream -y
    - apt-get install meson ninja-build -y

  script:
    - meson _build
    - ninja -C _build dist

check:
  stage: check
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - python3 -m pip install flake8

  script:
    - cd plugins
    - flake8 --select=F --ignore=F401



